import {
  AccountTreeTwoTone,
  EmojiObjects,
  People,
  RoomPreferencesOutlined,
  SettingsSuggest,
  Tune,
  VerifiedUser,
} from '@mui/icons-material';

// import { UserManagement } from '2_pages/adminUserManagement';
import { ModuleManagement } from '2_pages/adminModuleManagement';
import { SystemManagement } from '2_pages/adminSystemManagement';
import { AuditPage } from '2_pages/adminAuditPage';
import ObjectDetailsPage from '2_pages/objectDetails';
// import { MainPage } from '2_pages/adminMainPage';
import { useConfig } from '6_shared';
import { IContentList } from './types';

export const useGetAdminContentList = () => {
  const { config } = useConfig();

  const adminContentList: IContentList[] = [
    // {
    //   id: 'adminMain',
    //   title: 'Main',
    //   content: <MainPage />,
    //   isSidebar: false,
    //   isAccessable: true,
    //   icon: () => <RoomPreferencesOutlined />,
    // },
    // {
    //   id: 'adminUsers',
    //   title: 'User Management',
    //   content: <UserManagement />,
    //   isSidebar: true,
    //   isAccessable: true,
    //   icon: () => <People />,
    // },
    {
      id: 'modules',
      title: 'Module Management',
      content: <ModuleManagement />,
      isSidebar: true,
      isAccessable: true,
      icon: () => <SettingsSuggest />,
    },
    {
      id: 'environment',
      title: 'System Management',
      content: <SystemManagement />,
      isSidebar: true,
      isAccessable: true,
      icon: () => <Tune />,
    },
    {
      id: 'Audit',
      title: 'Audit',
      content: <AuditPage />,
      isSidebar: true,
      isAccessable: true,
      icon: () => <VerifiedUser />,
    },
    {
      id: 'objectDetails',
      title: 'Details',
      content: <ObjectDetailsPage />,
      isSidebar: false,
      isAccessable: true,
    },
    {
      id: 'solutions',
      title: 'Solutions',
      content: null,
      isSidebar: true,
      isAccessable: true,
      icon: () => <EmojiObjects />,
      child_count: 15,
    },
    {
      id: 'apacheAirflowIU',
      title: 'Apache Airflow',
      content: null,
      isAccessable: !!config._apacheAirflowIU,
      isSidebar: true,
      icon: () => <AccountTreeTwoTone />,
      p_id: 'solutions',
      link: config._apacheAirflowIU,
    },
    {
      id: 'apacheSupersetUI',
      title: 'Apache Superset',
      content: null,
      isAccessable: !!config._apacheSupersetUI,
      isSidebar: true,
      icon: () => <AccountTreeTwoTone />,
      p_id: 'solutions',
      link: config._apacheSupersetUI,
    },
    {
      id: 'camundaOperateUI',
      title: 'Camunda Operate',
      content: null,
      isAccessable: !!config._camundaOperateUI,
      isSidebar: true,
      icon: () => <AccountTreeTwoTone />,
      p_id: 'solutions',
      link: config._camundaOperateUI,
    },
    {
      id: 'camundaTasklistUI',
      title: 'Camunda Tasklist',
      content: null,
      isAccessable: !!config._camundaTasklistUI,
      isSidebar: true,
      icon: () => <AccountTreeTwoTone />,
      p_id: 'solutions',
      link: config._camundaTasklistUI,
    },
    {
      id: 'camundaOptimizeUI',
      title: 'Camunda Optimize',
      content: null,
      isAccessable: !!config._camundaOptimizeUI,
      isSidebar: true,
      icon: () => <AccountTreeTwoTone />,
      p_id: 'solutions',
      link: config._camundaOptimizeUI,
    },
    {
      id: 'camundaIdentityUI',
      title: 'Camunda Identity',
      content: null,
      isAccessable: !!config._camundaIdentityUI,
      isSidebar: true,
      icon: () => <AccountTreeTwoTone />,
      p_id: 'solutions',
      link: config._camundaIdentityUI,
    },
    {
      id: 'elasticSearchUI',
      title: 'Elasticsearch',
      content: null,
      isAccessable: !!config._elasticSearchUI,
      isSidebar: true,
      icon: () => <AccountTreeTwoTone />,
      p_id: 'solutions',
      link: config._elasticSearchUI,
    },
    {
      id: 'grafanaUI',
      title: 'Grafana',
      content: null,
      isAccessable: !!config._grafanaUI,
      isSidebar: true,
      icon: () => <AccountTreeTwoTone />,
      p_id: 'solutions',
      link: config._grafanaUI,
    },
    {
      id: 'kafkaIU',
      title: 'Kafka',
      content: null,
      isAccessable: !!config._kafkaUI,
      isSidebar: true,
      icon: () => <AccountTreeTwoTone />,
      p_id: 'solutions',
      link: config._kafkaUI,
    },
    {
      id: 'kibanaUI',
      title: 'Kibana',
      content: null,
      isAccessable: !!config._kibanaUI,
      isSidebar: true,
      icon: () => <AccountTreeTwoTone />,
      p_id: 'solutions',
      link: config._kibanaUI,
    },
    {
      id: 'minioUI',
      title: 'Minio',
      content: null,
      isAccessable: !!config._minioUI,
      isSidebar: true,
      icon: () => <AccountTreeTwoTone />,
      p_id: 'solutions',
      link: config._minioUI,
    },
    {
      id: 'nextcloud',
      title: 'Nextcloud',
      content: null,
      isAccessable: !!config._nextcloud,
      isSidebar: true,
      icon: () => <AccountTreeTwoTone />,
      p_id: 'solutions',
      link: config._nextcloud,
    },
    {
      id: 'openprojectUI',
      title: 'OpenProject',
      content: null,
      isAccessable: !!config._openprojectUI,
      isSidebar: true,
      icon: () => <AccountTreeTwoTone />,
      p_id: 'solutions',
      link: config._openprojectUI,
    },
    {
      id: 'pgAdminUI',
      title: 'pgAdminUI',
      content: null,
      isAccessable: !!config._pgAdminUI,
      isSidebar: true,
      icon: () => <AccountTreeTwoTone />,
      p_id: 'solutions',
      link: config._pgAdminUI,
    },
    {
      id: 'testrailUI',
      title: 'Testrail',
      content: null,
      isAccessable: !!config._testrailUI,
      isSidebar: true,
      icon: () => <AccountTreeTwoTone />,
      p_id: 'solutions',
      link: config._testrailUI,
    },
    {
      id: 'uptimeKumaUI',
      title: 'Uptime Kuma',
      content: null,
      isAccessable: !!config._uptimeKumaUI,
      isSidebar: true,
      icon: () => <AccountTreeTwoTone />,
      p_id: 'solutions',
      link: config._uptimeKumaUI,
    },
  ];

  return adminContentList;
};
