const defaultOperators: Record<string, Record<string, string>> = {
  string: {
    contains: 'contains',
    equals: 'equals',
    notEquals: 'notEquals',
    'ends with': 'endsWith',
    'starts with': 'startsWith',
    'is empty': 'isEmpty',
    'is not empty': 'isNotEmpty',
    'is any of': 'isAnyOf',
  },
  boolean: { is: 'is' },
  date: {
    is: 'is',
    'is not': 'not',
    'is after': 'after',
    'is on or after': 'onOrAfter',
    'is before': 'before',
    'is on or before': 'onOrBefore',
    'is empty': 'isEmpty',
    'is not empty': 'isNotEmpty',
  },
  dateTime: {
    is: 'is',
    'is not': 'isNot',
    'is after': 'isAfter',
    'is on or after': 'isOnOrAfter',
    'is before': 'isBefore',
    'is on or before': 'isOnOrBefore',
    'is empty': 'isEmpty',
    'is not empty': 'isNotEmpty',
  },
  number: {
    '=': '=',
    '!=': '!=',
    '<': '<',
    '<=': '<=',
    '>': '>',
    '>=': '>=',
    'is empty': 'isEmpty',
    'is not empty': 'isNotEmpty',
    'is any of': 'isAnyOf',
  },
  actions: {
    contains: 'contains',
    equals: 'equals',
    notEquals: 'notEquals',
    'ends with': 'endsWith',
    'starts with': 'startsWith',
    'is empty': 'isEmpty',
    'is not empty': 'isNotEmpty',
    'is any of': 'isAnyOf',
  },
  singleSelect: { is: 'is', 'is not': 'not', 'is any of': 'isAnyOf' },
};
export type FilterDataType = keyof typeof defaultOperators | string;
